In [2]:
import pandas as pd

In [3]:
info = {
    "Name" : ["Nobita", "Shizuka", "Doreamon", "Gian", "Sunio", "Degisugi"],
    "CGPA" : [7.08, 7.06, 5.0, 8.2, 6.5, 7.1]
}

df = pd.DataFrame(info)

print(df)

       Name  CGPA
0    Nobita  7.08
1   Shizuka  7.06
2  Doreamon  5.00
3      Gian  8.20
4     Sunio  6.50
5  Degisugi  7.10

In [4]:
df

       Name  CGPA
0    Nobita  7.08
1   Shizuka  7.06
2  Doreamon  5.00
3      Gian  8.20
4     Sunio  6.50
5  Degisugi  7.10

In [5]:
# Index Based ---> Position Based
s = pd.Series([1, 2, 3, 4, 5])
print(s)

# Indexing
print(s[4])

0    1
1    2
2    3
3    4
4    5
dtype: int64
5

In [6]:
# Label ---> named index based
s = pd.Series([23, 22, 30, 24], index=["Nobita", "Shizuka", "Doreamon", "Degisugi"])
print(s)

# Indexing:
print(s["Doreamon"])

Nobita      23
Shizuka     22
Doreamon    30
Degisugi    24
dtype: int64
30

In [7]:
# DataFrame ----> 2D labeled array

info = {
    "Name" : ["Nobita", "Shizuka", "Doreamon"],
    "Age" : [24, 23, 30],
    "CGPA" : [7.08, 6.05, 5.5]
}

df = pd.DataFrame(info)
print(df, type(df))

print(df.index) # RangeIndex(start=0, stop=3, step=1)
print(df.columns) # Index(['Name', 'Age', 'CGPA'], dtype='object')

       Name  Age  CGPA
0    Nobita   24  7.08
1   Shizuka   23  6.05
2  Doreamon   30  5.50 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [8]:
df

       Name  Age  CGPA
0    Nobita   24  7.08
1   Shizuka   23  6.05
2  Doreamon   30  5.50

In [9]:
# List Of List:
df = pd.DataFrame([["Nobita", 24], ["Shizuka", 23], ["Doreamon", 30]], columns=["Name", "Age"])
print(df)

       Name  Age
0    Nobita   24
1   Shizuka   23
2  Doreamon   30

In [10]:
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
# CSV Data:-

df_csv = pd.read_csv("employee_data.csv")
print(df_csv)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [12]:
df_csv

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [13]:
df_csv.head() # Starting 5 rows

df_csv.tail(2) # Last 5 rows

df_csv.sample() # Using print any random rows

df_csv.info() # Get basic info about the data

df_csv.shape  # Give the how many 'rows' and 'columns' in the data

df_csv.describe() # Using the they gives me numerical information like mean, min, max

df_csv.columns # Gives the all columns in data

df_csv.nunique() # Gives the all unique values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

# Work with real dataset like AQI

In [14]:
df = pd.read_csv("globalAirQuality.csv")

In [15]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [16]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [17]:
df.shape

(18000, 15)

In [18]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [19]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [48]:
# Selecting the Columns :

df["city"]
df[["city", "aqi"]]


df.loc[0] # Print the all row data
df.loc[0:2] # start idx : end idx - (End idx is inclusive) 

df.iloc[0] # Print the all row data
df.iloc[0:2] # start idx : end idx - (End idx is Exclusive) 

#Cells - Rows & Columns
df.loc[0, "aqi"]

df.loc[0, ["city", "aqi"]]
df.loc[0:2, ["city", "aqi"]]
# df.iloc[0:2, ["city", "aqi"]]

df.columns
df.iloc[0:3, 2] 

df.loc[0:3, ["country", "city", "latitude", "longitude"]]

#Same I am printing using the iloc
df.iloc[0:3, 1:5]

# Cell at & iat
df.at[0, "city"]
df.iat[0, 2]

cities = df["city"].copy()
cities[0] = "Mumbai"
cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [49]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [62]:
# Filtering The Data:-
df[df["aqi"] > 100] # find greater than 100 values

df[(df["aqi"] > 100) & (df["temperature"] > 30)] # Multiple conditions

df[df["aqi"] > 100][["city", "aqi"]] #Greater than 100 with columns city and aqi only

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]] #Greater than 100 with columns city and aqi only

aqi_data

aqi_data.iloc[0]

# aqi_data.loc[0]
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

In [67]:
# Query rules: query() returns the copy of the data

df.query("aqi > 100")

df.query("aqi > 100 & temperature > 30")[["aqi", "temperature"]]

# @ to reference Python vars

aqi_var = 100
df.query("aqi > @aqi_var")

# query returns the copy of the data not view the data
aqi_data = df.query("aqi > 100 & temperature > 30")[["aqi", "temperature"]].copy()

In [68]:
aqi_data

       aqi  temperature
6      155       36.729
7      115       37.891
14     121       34.481
17     127       36.193
25     113       31.289
...    ...          ...
17947  107       32.584
17950  140       36.885
17975  111       30.761
17976  146       30.909
17991  104       32.556

[2384 rows x 2 columns]

# Missing values - Cleaning data

In [69]:
# Missing values - Cleaning data

df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [80]:
df.isnull() # Find missing values

df.isnull().sum() # Count the null value for each component

df.dropna() #Drop the ROW if there is null value available
df.dropna(axis=1) #Drop the COLUMNS if there is null value available

df.fillna(0) # Fill with the missing values any missing value
# df["age"].fillna(df["age"].mean())

age_mean = df["age"].mean()

cleaned_data = df.copy() # Step - 1: create the copy for original data
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean) # step - 2: access the cleaned_data and add the age_mean value

# cleaned_data

#ffill(): carrying forward the last known (previous) non-missing value.
df.ffill()

#bfill(): filling missing values using the next available (future) non-missing value.
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [86]:
# Handling the Duplicates

df.duplicated() #Entire data

df[["country", "gender"]].duplicated() # Columns wise

df2 = df.copy()

df.drop_duplicates(inplace=True)

In [88]:
df2 = df

In [103]:
#Data Types
df.dtypes

#Create the new data type
df2 = df.copy()

df2 = df.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

#to_datetime() :
date_str = pd.Series([pd.to_datetime("2026-12-31")]) # DateTime64DType
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [109]:
# Handle strings: 

# df["gender"].str.lower()
# df["gender"].str.upper()
# df["gender"].str.Capitalize()

df["name"].str.split(" ") # John Doe ---> [John, Doe]

df["country"].str.contains("US")
df["country"].str.contains("india", case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [99]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0