In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IRIS.csv")
df.head(10)

df.shape

(150, 5)

In [3]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [4]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.query("petal_length > 4.5")

df[df['species'] == 'Iris-virginica' ] # 1st techgnique

df.query("species == 'Iris-virginica'") # 2nd technique

df.query("petal_length > 4.5 and species == 'Iris-virginica'")
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
# Groupby species and compute

# df.groupby("petal_length").agg('mean')

df.groupby('species')['petal_length'].mean()

df.groupby('species')['petal_width'].max()

# Standard derivarion
df.groupby('species')['sepal_width'].std()

df.groupby('species').agg({
    'sepal_length': 'mean',
    'petal_width': 'max',
    'sepal_width': 'std'
})

                 sepal_length  petal_width  sepal_width
species
Iris-setosa             5.006          0.6     0.381024
Iris-versicolor         5.936          1.8     0.313798
Iris-virginica          6.588          2.5     0.322497

In [7]:
# Create a new column: "petal_ratio"=petal_length / petal_width
#  For each species,find the average petal_ratio.

df['petal_ratio'] = df['petal_length'] / df['petal_width']

In [8]:
df.groupby('species')['petal_ratio'].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

# TITANIC DATASET

In [9]:
df = pd.read_csv('Titanic-Dataset.csv')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
# Display only columns: multiple and selected columns
df[["Name", "Sex", "Age", "Fare", "Survived"]]


df.query("(Sex == 'female') & ( Fare > 30) ")

df.groupby('Pclass')['Survived'].mean()
df.groupby('Pclass')['Fare'].mean()
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

# Practise with ChatGPT

In [13]:
df = pd.read_csv('data.csv')

In [14]:
df

    ID    Name  Age  Salary Department  Gender  Math  Science
0    1    Alex   25   50000         IT    Male    80       78
1    2    Riya   30   60000         HR  Female    70       72
2    3     Sam   22   45000         IT    Male    65       60
3    4   Meera   28   52000    Finance  Female    75       80
4    5    John   45   80000         IT    Male    90       88
5    6    Arun   35   73000    Finance    Male    88       85
6    7    Tina   19   30000         HR  Female    55       58
7    8   Karan   40   65000         HR    Male    68       70
8    9  Sophia   33   72000         IT  Female    92       94
9   10  Vikram   29   58000    Finance    Male    78       75
10  11    Neha   31   61000         HR  Female    83       82
11  12     Raj   27   49000         IT    Male    60       63
12  13   Emily   50   90000    Finance  Female    95       90
13  14    Aman   23   31000    Finance    Male    67       61
14  15    Sara   26   54000         IT  Female    72       76
15  16   Kabir   38   76000         HR    Male    85       87
16  17    Lily   20   35000    Finance  Female    59       57
17  18   Rohit   42   82000         IT    Male    91       89
18  19    Nora   24   44000         HR  Female    66       64
19  20     Dev   36   70000    Finance    Male    89       86

In [15]:
df.head()

   ID   Name  Age  Salary Department  Gender  Math  Science
0   1   Alex   25   50000         IT    Male    80       78
1   2   Riya   30   60000         HR  Female    70       72
2   3    Sam   22   45000         IT    Male    65       60
3   4  Meera   28   52000    Finance  Female    75       80
4   5   John   45   80000         IT    Male    90       88

In [16]:
df.columns

Index(['ID', 'Name', 'Age', 'Salary', 'Department', 'Gender', 'Math',
       'Science'],
      dtype='object')

In [17]:
df.shape

(20, 8)

In [18]:
df.describe()

             ID        Age        Salary       Math    Science
count  20.00000  20.000000     20.000000  20.000000  20.000000
mean   10.50000  31.150000  58850.000000  76.400000  75.750000
std     5.91608   8.591765  17205.491779  12.360378  11.968709
min     1.00000  19.000000  30000.000000  55.000000  57.000000
25%     5.75000  24.750000  48000.000000  66.750000  63.750000
50%    10.50000  29.500000  59000.000000  76.500000  77.000000
75%    15.25000  36.500000  72250.000000  88.250000  86.250000
max    20.00000  50.000000  90000.000000  95.000000  94.000000

In [19]:
df["Age"]

0     25
1     30
2     22
3     28
4     45
5     35
6     19
7     40
8     33
9     29
10    31
11    27
12    50
13    23
14    26
15    38
16    20
17    42
18    24
19    36
Name: Age, dtype: int64

In [20]:
df[['Name', 'Age']].head(10)

     Name  Age
0    Alex   25
1    Riya   30
2     Sam   22
3   Meera   28
4    John   45
5    Arun   35
6    Tina   19
7   Karan   40
8  Sophia   33
9  Vikram   29

In [21]:
df[df['Age'] > 30]

    ID    Name  Age  Salary Department  Gender  Math  Science
4    5    John   45   80000         IT    Male    90       88
5    6    Arun   35   73000    Finance    Male    88       85
7    8   Karan   40   65000         HR    Male    68       70
8    9  Sophia   33   72000         IT  Female    92       94
10  11    Neha   31   61000         HR  Female    83       82
12  13   Emily   50   90000    Finance  Female    95       90
15  16   Kabir   38   76000         HR    Male    85       87
17  18   Rohit   42   82000         IT    Male    91       89
19  20     Dev   36   70000    Finance    Male    89       86

In [22]:
df.isnull().sum()

ID            0
Name          0
Age           0
Salary        0
Department    0
Gender        0
Math          0
Science       0
dtype: int64

In [23]:
df.dropna()

    ID    Name  Age  Salary Department  Gender  Math  Science
0    1    Alex   25   50000         IT    Male    80       78
1    2    Riya   30   60000         HR  Female    70       72
2    3     Sam   22   45000         IT    Male    65       60
3    4   Meera   28   52000    Finance  Female    75       80
4    5    John   45   80000         IT    Male    90       88
5    6    Arun   35   73000    Finance    Male    88       85
6    7    Tina   19   30000         HR  Female    55       58
7    8   Karan   40   65000         HR    Male    68       70
8    9  Sophia   33   72000         IT  Female    92       94
9   10  Vikram   29   58000    Finance    Male    78       75
10  11    Neha   31   61000         HR  Female    83       82
11  12     Raj   27   49000         IT    Male    60       63
12  13   Emily   50   90000    Finance  Female    95       90
13  14    Aman   23   31000    Finance    Male    67       61
14  15    Sara   26   54000         IT  Female    72       76
15  16   Kabir   38   76000         HR    Male    85       87
16  17    Lily   20   35000    Finance  Female    59       57
17  18   Rohit   42   82000         IT    Male    91       89
18  19    Nora   24   44000         HR  Female    66       64
19  20     Dev   36   70000    Finance    Male    89       86

In [24]:
# Filtering the data using these 2 technique

df.query('(Salary > 5000) & (Age > 25)') 

df[(df['Age'] > 25) & (df['Salary'] > 5000)]

    ID    Name  Age  Salary Department  Gender  Math  Science
1    2    Riya   30   60000         HR  Female    70       72
3    4   Meera   28   52000    Finance  Female    75       80
4    5    John   45   80000         IT    Male    90       88
5    6    Arun   35   73000    Finance    Male    88       85
7    8   Karan   40   65000         HR    Male    68       70
8    9  Sophia   33   72000         IT  Female    92       94
9   10  Vikram   29   58000    Finance    Male    78       75
10  11    Neha   31   61000         HR  Female    83       82
11  12     Raj   27   49000         IT    Male    60       63
12  13   Emily   50   90000    Finance  Female    95       90
14  15    Sara   26   54000         IT  Female    72       76
15  16   Kabir   38   76000         HR    Male    85       87
17  18   Rohit   42   82000         IT    Male    91       89
19  20     Dev   36   70000    Finance    Male    89       86

In [25]:
# Replace missing Age values with the average Age.
avg_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(avg_age)

df['Age'].fillna(df['Age'].mean())

0     25
1     30
2     22
3     28
4     45
5     35
6     19
7     40
8     33
9     29
10    31
11    27
12    50
13    23
14    26
15    38
16    20
17    42
18    24
19    36
Name: Age, dtype: int64

In [26]:
# Sort the dataset by Salary in descending order.
# df["Salary"].sort_values(ascending=False)

df.sort_values('Salary', ascending=False)

    ID    Name  Age  Salary Department  Gender  Math  Science
12  13   Emily   50   90000    Finance  Female    95       90
17  18   Rohit   42   82000         IT    Male    91       89
4    5    John   45   80000         IT    Male    90       88
15  16   Kabir   38   76000         HR    Male    85       87
5    6    Arun   35   73000    Finance    Male    88       85
8    9  Sophia   33   72000         IT  Female    92       94
19  20     Dev   36   70000    Finance    Male    89       86
7    8   Karan   40   65000         HR    Male    68       70
10  11    Neha   31   61000         HR  Female    83       82
1    2    Riya   30   60000         HR  Female    70       72
9   10  Vikram   29   58000    Finance    Male    78       75
14  15    Sara   26   54000         IT  Female    72       76
3    4   Meera   28   52000    Finance  Female    75       80
0    1    Alex   25   50000         IT    Male    80       78
11  12     Raj   27   49000         IT    Male    60       63
2    3     Sam   22   45000         IT    Male    65       60
18  19    Nora   24   44000         HR  Female    66       64
16  17    Lily   20   35000    Finance  Female    59       57
13  14    Aman   23   31000    Finance    Male    67       61
6    7    Tina   19   30000         HR  Female    55       58

In [27]:
# Group by Department and find the average salary.

df.groupby('Department')['Salary'].mean()

Department
Finance    58428.571429
HR         56000.000000
IT         61714.285714
Name: Salary, dtype: float64

In [28]:
# Group by Department and count number of employees

df.groupby("Department")['Name'].count()

Department
Finance    7
HR         6
IT         7
Name: Name, dtype: int64

In [29]:
# Add a new column “Bonus” = Salary * 0.10.

df['Bonus'] = df["Salary"] * 0.10
df

    ID    Name  Age  Salary Department  Gender  Math  Science   Bonus
0    1    Alex   25   50000         IT    Male    80       78  5000.0
1    2    Riya   30   60000         HR  Female    70       72  6000.0
2    3     Sam   22   45000         IT    Male    65       60  4500.0
3    4   Meera   28   52000    Finance  Female    75       80  5200.0
4    5    John   45   80000         IT    Male    90       88  8000.0
5    6    Arun   35   73000    Finance    Male    88       85  7300.0
6    7    Tina   19   30000         HR  Female    55       58  3000.0
7    8   Karan   40   65000         HR    Male    68       70  6500.0
8    9  Sophia   33   72000         IT  Female    92       94  7200.0
9   10  Vikram   29   58000    Finance    Male    78       75  5800.0
10  11    Neha   31   61000         HR  Female    83       82  6100.0
11  12     Raj   27   49000         IT    Male    60       63  4900.0
12  13   Emily   50   90000    Finance  Female    95       90  9000.0
13  14    Aman   23   31000    Finance    Male    67       61  3100.0
14  15    Sara   26   54000         IT  Female    72       76  5400.0
15  16   Kabir   38   76000         HR    Male    85       87  7600.0
16  17    Lily   20   35000    Finance  Female    59       57  3500.0
17  18   Rohit   42   82000         IT    Male    91       89  8200.0
18  19    Nora   24   44000         HR  Female    66       64  4400.0
19  20     Dev   36   70000    Finance    Male    89       86  7000.0

In [30]:
# Rename Salary column to “Income”.

df.rename(columns = {'Salary': 'Income'})

    ID    Name  Age  Income Department  Gender  Math  Science   Bonus
0    1    Alex   25   50000         IT    Male    80       78  5000.0
1    2    Riya   30   60000         HR  Female    70       72  6000.0
2    3     Sam   22   45000         IT    Male    65       60  4500.0
3    4   Meera   28   52000    Finance  Female    75       80  5200.0
4    5    John   45   80000         IT    Male    90       88  8000.0
5    6    Arun   35   73000    Finance    Male    88       85  7300.0
6    7    Tina   19   30000         HR  Female    55       58  3000.0
7    8   Karan   40   65000         HR    Male    68       70  6500.0
8    9  Sophia   33   72000         IT  Female    92       94  7200.0
9   10  Vikram   29   58000    Finance    Male    78       75  5800.0
10  11    Neha   31   61000         HR  Female    83       82  6100.0
11  12     Raj   27   49000         IT    Male    60       63  4900.0
12  13   Emily   50   90000    Finance  Female    95       90  9000.0
13  14    Aman   23   31000    Finance    Male    67       61  3100.0
14  15    Sara   26   54000         IT  Female    72       76  5400.0
15  16   Kabir   38   76000         HR    Male    85       87  7600.0
16  17    Lily   20   35000    Finance  Female    59       57  3500.0
17  18   Rohit   42   82000         IT    Male    91       89  8200.0
18  19    Nora   24   44000         HR  Female    66       64  4400.0
19  20     Dev   36   70000    Finance    Male    89       86  7000.0

In [31]:
# Remove the Bonus column.
df.drop(columns = ['Bonus'])

    ID    Name  Age  Salary Department  Gender  Math  Science
0    1    Alex   25   50000         IT    Male    80       78
1    2    Riya   30   60000         HR  Female    70       72
2    3     Sam   22   45000         IT    Male    65       60
3    4   Meera   28   52000    Finance  Female    75       80
4    5    John   45   80000         IT    Male    90       88
5    6    Arun   35   73000    Finance    Male    88       85
6    7    Tina   19   30000         HR  Female    55       58
7    8   Karan   40   65000         HR    Male    68       70
8    9  Sophia   33   72000         IT  Female    92       94
9   10  Vikram   29   58000    Finance    Male    78       75
10  11    Neha   31   61000         HR  Female    83       82
11  12     Raj   27   49000         IT    Male    60       63
12  13   Emily   50   90000    Finance  Female    95       90
13  14    Aman   23   31000    Finance    Male    67       61
14  15    Sara   26   54000         IT  Female    72       76
15  16   Kabir   38   76000         HR    Male    85       87
16  17    Lily   20   35000    Finance  Female    59       57
17  18   Rohit   42   82000         IT    Male    91       89
18  19    Nora   24   44000         HR  Female    66       64
19  20     Dev   36   70000    Finance    Male    89       86

In [53]:
# Select the top 5 highest salaries.

df.nlargest(5, 'Salary')

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group,rolling_salary
12,13,EMILY,50,90000,Finance,Female,95,90,9000.0,Senior,66666.666667
17,18,ROHIT,42,82000,IT,Male,91,89,8200.0,Senior,64333.333333
4,5,JOHN,45,80000,IT,Male,90,88,8000.0,Senior,59000.000000
15,16,KABIR,38,76000,HR,Male,85,87,7600.0,Adult,53666.666667
5,6,ARUN,35,73000,Finance,Male,88,85,7300.0,Adult,68333.333333

In [33]:
# Convert all names to uppercase.

df['Name'] = df['Name'].str.upper()

In [34]:
df

    ID    Name  Age  Salary Department  Gender  Math  Science   Bonus
0    1    ALEX   25   50000         IT    Male    80       78  5000.0
1    2    RIYA   30   60000         HR  Female    70       72  6000.0
2    3     SAM   22   45000         IT    Male    65       60  4500.0
3    4   MEERA   28   52000    Finance  Female    75       80  5200.0
4    5    JOHN   45   80000         IT    Male    90       88  8000.0
5    6    ARUN   35   73000    Finance    Male    88       85  7300.0
6    7    TINA   19   30000         HR  Female    55       58  3000.0
7    8   KARAN   40   65000         HR    Male    68       70  6500.0
8    9  SOPHIA   33   72000         IT  Female    92       94  7200.0
9   10  VIKRAM   29   58000    Finance    Male    78       75  5800.0
10  11    NEHA   31   61000         HR  Female    83       82  6100.0
11  12     RAJ   27   49000         IT    Male    60       63  4900.0
12  13   EMILY   50   90000    Finance  Female    95       90  9000.0
13  14    AMAN   23   31000    Finance    Male    67       61  3100.0
14  15    SARA   26   54000         IT  Female    72       76  5400.0
15  16   KABIR   38   76000         HR    Male    85       87  7600.0
16  17    LILY   20   35000    Finance  Female    59       57  3500.0
17  18   ROHIT   42   82000         IT    Male    91       89  8200.0
18  19    NORA   24   44000         HR  Female    66       64  4400.0
19  20     DEV   36   70000    Finance    Male    89       86  7000.0

In [35]:
# Create a new column Age_Group using custom logic: Teen / Adult / Senior.
def age_group(x):
    if x < 18:
        return "Teen"
    elif x < 40:
        return "Adult"
    else:
        return "Senior"
df["Age_Group"] = df['Age'].apply(age_group)

In [36]:
df

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group
0,1,ALEX,25,50000,IT,Male,80,78,5000.0,Adult
1,2,RIYA,30,60000,HR,Female,70,72,6000.0,Adult
2,3,SAM,22,45000,IT,Male,65,60,4500.0,Adult
3,4,MEERA,28,52000,Finance,Female,75,80,5200.0,Adult
4,5,JOHN,45,80000,IT,Male,90,88,8000.0,Senior
5,6,ARUN,35,73000,Finance,Male,88,85,7300.0,Adult
6,7,TINA,19,30000,HR,Female,55,58,3000.0,Adult
7,8,KARAN,40,65000,HR,Male,68,70,6500.0,Senior
8,9,SOPHIA,33,72000,IT,Female,92,94,7200.0,Adult
9,10,VIKRAM,29,58000,Finance,Male,78,75,5800.0,Adult
10,11,NEHA,31,61000,HR,Female,83,82,6100.0,Adult
11,12,RAJ,27,49000,IT,Male,60,63,4900.0,Adult
12,13,EMILY,50,90000,Finance,Female,95,90,9000.0,Senior
13,14,AMAN,23,31000,Finance,Male,67,61,3100.0,Adult
14,15,SARA,26,54000,IT,Female,72,76,5400.0,Adult
15,16,KABIR,38,76000,HR,Male,85,87,7600.0,Adult
16,17,LILY,20,35000,Finance,Female,59,57,3500.0,Adult
17,18,ROHIT,42,82000,IT,Male,91,89,8200.0,Senior
18,19,NORA,24,44000,HR,Female,66,64,4400.0,Adult
19,20,DEV,36,70000,Finance,Male,89,86,7000.0,Adult

In [37]:
# Create a pivot table showing average Salary per Department per Gender.

df.pivot_table(
    values = 'Salary',
    index= 'Department',
    columns = 'Gender',
    aggfunc = 'mean'
)

Gender       Female     Male
Department
Finance     59000.0  58000.0
HR          48750.0  70500.0
IT          63000.0  61200.0

In [39]:
# Melt the DataFrame: Convert Math and Science into one long format column.
df.melt(
    id_vars = ['Name'],
    value_vars = ['Math', 'Science'],
    var_name = 'MS veriables',
    value_name = "MS_values"
)

      Name MS veriables  MS_values
0     ALEX         Math         80
1     RIYA         Math         70
2      SAM         Math         65
3    MEERA         Math         75
4     JOHN         Math         90
5     ARUN         Math         88
6     TINA         Math         55
7    KARAN         Math         68
8   SOPHIA         Math         92
9   VIKRAM         Math         78
10    NEHA         Math         83
11     RAJ         Math         60
12   EMILY         Math         95
13    AMAN         Math         67
14    SARA         Math         72
15   KABIR         Math         85
16    LILY         Math         59
17   ROHIT         Math         91
18    NORA         Math         66
19     DEV         Math         89
20    ALEX      Science         78
21    RIYA      Science         72
22     SAM      Science         60
23   MEERA      Science         80
24    JOHN      Science         88
25    ARUN      Science         85
26    TINA      Science         58
27   KARAN      Science         70
28  SOPHIA      Science         94
29  VIKRAM      Science         75
30    NEHA      Science         82
31     RAJ      Science         63
32   EMILY      Science         90
33    AMAN      Science         61
34    SARA      Science         76
35   KABIR      Science         87
36    LILY      Science         57
37   ROHIT      Science         89
38    NORA      Science         64
39     DEV      Science         86

In [42]:
# Remove duplicate rows based only on the Name column.

df.drop_duplicates(subset='Name', inplace=True)

In [43]:
df

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group
0,1,ALEX,25,50000,IT,Male,80,78,5000.0,Adult
1,2,RIYA,30,60000,HR,Female,70,72,6000.0,Adult
2,3,SAM,22,45000,IT,Male,65,60,4500.0,Adult
3,4,MEERA,28,52000,Finance,Female,75,80,5200.0,Adult
4,5,JOHN,45,80000,IT,Male,90,88,8000.0,Senior
5,6,ARUN,35,73000,Finance,Male,88,85,7300.0,Adult
6,7,TINA,19,30000,HR,Female,55,58,3000.0,Adult
7,8,KARAN,40,65000,HR,Male,68,70,6500.0,Senior
8,9,SOPHIA,33,72000,IT,Female,92,94,7200.0,Adult
9,10,VIKRAM,29,58000,Finance,Male,78,75,5800.0,Adult
10,11,NEHA,31,61000,HR,Female,83,82,6100.0,Adult
11,12,RAJ,27,49000,IT,Male,60,63,4900.0,Adult
12,13,EMILY,50,90000,Finance,Female,95,90,9000.0,Senior
13,14,AMAN,23,31000,Finance,Male,67,61,3100.0,Adult
14,15,SARA,26,54000,IT,Female,72,76,5400.0,Adult
15,16,KABIR,38,76000,HR,Male,85,87,7600.0,Adult
16,17,LILY,20,35000,Finance,Female,59,57,3500.0,Adult
17,18,ROHIT,42,82000,IT,Male,91,89,8200.0,Senior
18,19,NORA,24,44000,HR,Female,66,64,4400.0,Adult
19,20,DEV,36,70000,Finance,Male,89,86,7000.0,Adult

In [44]:
# Calculate a rolling average of Salary with window size = 3.
df['rolling_salary'] = df['Salary'].rolling(window=3).mean()

In [45]:
df

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group,rolling_salary
0,1,ALEX,25,50000,IT,Male,80,78,5000.0,Adult,NaN
1,2,RIYA,30,60000,HR,Female,70,72,6000.0,Adult,NaN
2,3,SAM,22,45000,IT,Male,65,60,4500.0,Adult,51666.666667
3,4,MEERA,28,52000,Finance,Female,75,80,5200.0,Adult,52333.333333
4,5,JOHN,45,80000,IT,Male,90,88,8000.0,Senior,59000.000000
5,6,ARUN,35,73000,Finance,Male,88,85,7300.0,Adult,68333.333333
6,7,TINA,19,30000,HR,Female,55,58,3000.0,Adult,61000.000000
7,8,KARAN,40,65000,HR,Male,68,70,6500.0,Senior,56000.000000
8,9,SOPHIA,33,72000,IT,Female,92,94,7200.0,Adult,55666.666667
9,10,VIKRAM,29,58000,Finance,Male,78,75,5800.0,Adult,65000.000000
10,11,NEHA,31,61000,HR,Female,83,82,6100.0,Adult,63666.666667
11,12,RAJ,27,49000,IT,Male,60,63,4900.0,Adult,56000.000000
12,13,EMILY,50,90000,Finance,Female,95,90,9000.0,Senior,66666.666667
13,14,AMAN,23,31000,Finance,Male,67,61,3100.0,Adult,56666.666667
14,15,SARA,26,54000,IT,Female,72,76,5400.0,Adult,58333.333333
15,16,KABIR,38,76000,HR,Male,85,87,7600.0,Adult,53666.666667
16,17,LILY,20,35000,Finance,Female,59,57,3500.0,Adult,55000.000000
17,18,ROHIT,42,82000,IT,Male,91,89,8200.0,Senior,64333.333333
18,19,NORA,24,44000,HR,Female,66,64,4400.0,Adult,53666.666667
19,20,DEV,36,70000,Finance,Male,89,86,7000.0,Adult,65333.333333

In [47]:
# Select all rows where Name starts with the letter “A”.
df[df['Name'].str.startswith('A')]

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group,rolling_salary
0,1,ALEX,25,50000,IT,Male,80,78,5000.0,Adult,NaN
5,6,ARUN,35,73000,Finance,Male,88,85,7300.0,Adult,68333.333333
13,14,AMAN,23,31000,Finance,Male,67,61,3100.0,Adult,56666.666667

In [48]:
# Replace all negative Salary values with 0.
df['Salary'] = df['Salary'].apply(lambda x:0 if x < 0 else x)

In [49]:
df

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group,rolling_salary
0,1,ALEX,25,50000,IT,Male,80,78,5000.0,Adult,NaN
1,2,RIYA,30,60000,HR,Female,70,72,6000.0,Adult,NaN
2,3,SAM,22,45000,IT,Male,65,60,4500.0,Adult,51666.666667
3,4,MEERA,28,52000,Finance,Female,75,80,5200.0,Adult,52333.333333
4,5,JOHN,45,80000,IT,Male,90,88,8000.0,Senior,59000.000000
5,6,ARUN,35,73000,Finance,Male,88,85,7300.0,Adult,68333.333333
6,7,TINA,19,30000,HR,Female,55,58,3000.0,Adult,61000.000000
7,8,KARAN,40,65000,HR,Male,68,70,6500.0,Senior,56000.000000
8,9,SOPHIA,33,72000,IT,Female,92,94,7200.0,Adult,55666.666667
9,10,VIKRAM,29,58000,Finance,Male,78,75,5800.0,Adult,65000.000000
10,11,NEHA,31,61000,HR,Female,83,82,6100.0,Adult,63666.666667
11,12,RAJ,27,49000,IT,Male,60,63,4900.0,Adult,56000.000000
12,13,EMILY,50,90000,Finance,Female,95,90,9000.0,Senior,66666.666667
13,14,AMAN,23,31000,Finance,Male,67,61,3100.0,Adult,56666.666667
14,15,SARA,26,54000,IT,Female,72,76,5400.0,Adult,58333.333333
15,16,KABIR,38,76000,HR,Male,85,87,7600.0,Adult,53666.666667
16,17,LILY,20,35000,Finance,Female,59,57,3500.0,Adult,55000.000000
17,18,ROHIT,42,82000,IT,Male,91,89,8200.0,Senior,64333.333333
18,19,NORA,24,44000,HR,Female,66,64,4400.0,Adult,53666.666667
19,20,DEV,36,70000,Finance,Male,89,86,7000.0,Adult,65333.333333

In [50]:
# Read multiple CSV files and combine them using concat().
df2 = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5, 8, 10, 12, 15, 20, 22, 25],
    "City": ["Delhi", "Mumbai", "Chennai", "Pune", "Bangalore",
             "Kolkata", "Hyderabad", "Jaipur", "Surat",
             "Ahmedabad", "Goa", "Indore"],
    "Experience": [2, 5, 1, 7, 10, 3, 6, 4, 8, 12, 5, 9]
})

In [52]:
pd.concat([df, df2], ignore_index=True)

,ID,Name,Age,Salary,Department,Gender,Math,Science,Bonus,Age_Group,rolling_salary,City,Experience
0,1,ALEX,25.0,50000.0,IT,Male,80.0,78.0,5000.0,Adult,NaN,NaN,NaN
1,2,RIYA,30.0,60000.0,HR,Female,70.0,72.0,6000.0,Adult,NaN,NaN,NaN
2,3,SAM,22.0,45000.0,IT,Male,65.0,60.0,4500.0,Adult,51666.666667,NaN,NaN
3,4,MEERA,28.0,52000.0,Finance,Female,75.0,80.0,5200.0,Adult,52333.333333,NaN,NaN
4,5,JOHN,45.0,80000.0,IT,Male,90.0,88.0,8000.0,Senior,59000.000000,NaN,NaN
5,6,ARUN,35.0,73000.0,Finance,Male,88.0,85.0,7300.0,Adult,68333.333333,NaN,NaN
6,7,TINA,19.0,30000.0,HR,Female,55.0,58.0,3000.0,Adult,61000.000000,NaN,NaN
7,8,KARAN,40.0,65000.0,HR,Male,68.0,70.0,6500.0,Senior,56000.000000,NaN,NaN
8,9,SOPHIA,33.0,72000.0,IT,Female,92.0,94.0,7200.0,Adult,55666.666667,NaN,NaN
9,10,VIKRAM,29.0,58000.0,Finance,Male,78.0,75.0,5800.0,Adult,65000.000000,NaN,NaN
10,11,NEHA,31.0,61000.0,HR,Female,83.0,82.0,6100.0,Adult,63666.666667,NaN,NaN
11,12,RAJ,27.0,49000.0,IT,Male,60.0,63.0,4900.0,Adult,56000.000000,NaN,NaN
12,13,EMILY,50.0,90000.0,Finance,Female,95.0,90.0,9000.0,Senior,66666.666667,NaN,NaN
13,14,AMAN,23.0,31000.0,Finance,Male,67.0,61.0,3100.0,Adult,56666.666667,NaN,NaN
14,15,SARA,26.0,54000.0,IT,Female,72.0,76.0,5400.0,Adult,58333.333333,NaN,NaN
15,16,KABIR,38.0,76000.0,HR,Male,85.0,87.0,7600.0,Adult,53666.666667,NaN,NaN
16,17,LILY,20.0,35000.0,Finance,Female,59.0,57.0,3500.0,Adult,55000.000000,NaN,NaN
17,18,ROHIT,42.0,82000.0,IT,Male,91.0,89.0,8200.0,Senior,64333.333333,NaN,NaN
18,19,NORA,24.0,44000.0,HR,Female,66.0,64.0,4400.0,Adult,53666.666667,NaN,NaN
19,20,DEV,36.0,70000.0,Finance,Male,89.0,86.0,7000.0,Adult,65333.333333,NaN,NaN
20,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi,2.0
21,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai,5.0
22,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chennai,1.0
23,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pune,7.0
24,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore,10.0
25,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kolkata,3.0
26,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad,6.0
27,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jaipur,4.0
28,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Surat,8.0
29,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ahmedabad,12.0
30,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Goa,5.0
31,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Indore,9.0