In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [67]:
df = pd.read_csv("HousePricePrediction.csv")

In [68]:
df.head()

   Id  MSSubClass MSZoning  ...  BsmtFinSF2 TotalBsmtSF SalePrice
0   0          60       RL  ...         0.0       856.0  208500.0
1   1          20       RL  ...         0.0      1262.0  181500.0
2   2          60       RL  ...         0.0       920.0  223500.0
3   3          70       RL  ...         0.0       756.0  140000.0
4   4          60       RL  ...         0.0      1145.0  250000.0

[5 rows x 13 columns]

In [69]:
df.sample(10)

        Id  MSSubClass MSZoning  ...  BsmtFinSF2 TotalBsmtSF SalePrice
1796  1796          50       RL  ...         0.0       795.0       NaN
1736  1736          20       RL  ...        92.0      2014.0       NaN
407    407          70       RL  ...         0.0       840.0  177000.0
572    572          60       RL  ...         0.0       846.0  224500.0
1315  1315          60       RL  ...       276.0       952.0  206900.0
791    791          80       RL  ...         0.0      1029.0  146800.0
2653  2653          20       RL  ...         0.0      1721.0       NaN
2130  2130          50       RM  ...         0.0      1272.0       NaN
290    290          60       RL  ...         0.0      1079.0  233230.0
186    186          80       RL  ...         0.0      1188.0  173000.0

[10 rows x 13 columns]

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [71]:
df.describe()

                Id   MSSubClass  ...  TotalBsmtSF      SalePrice
count  2919.000000  2919.000000  ...  2918.000000    1460.000000
mean   1459.000000    57.137718  ...  1051.777587  180921.195890
std     842.787043    42.517628  ...   440.766258   79442.502883
min       0.000000    20.000000  ...     0.000000   34900.000000
25%     729.500000    20.000000  ...   793.000000  129975.000000
50%    1459.000000    50.000000  ...   989.500000  163000.000000
75%    2188.500000    70.000000  ...  1302.000000  214000.000000
max    2918.000000   190.000000  ...  6110.000000  755000.000000

[8 rows x 9 columns]

In [72]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [73]:
categorical_cols = df.select_dtypes(include=["object"]).columns
numerical_cols = df.select_dtypes(include=["number"]).columns

In [74]:
categorical_cols

Index(['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st'], dtype='object')

In [75]:
numerical_cols

Index(['Id', 'MSSubClass', 'LotArea', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'BsmtFinSF2', 'TotalBsmtSF', 'SalePrice'],
      dtype='object')

In [76]:
# Filling the missing values 

from sklearn.impute import SimpleImputer

num_impute = SimpleImputer(strategy="mean")
df[numerical_cols] = num_impute.fit_transform(df[numerical_cols])

In [77]:
df.head()

    Id  MSSubClass MSZoning  ...  BsmtFinSF2 TotalBsmtSF SalePrice
0  0.0        60.0       RL  ...         0.0       856.0  208500.0
1  1.0        20.0       RL  ...         0.0      1262.0  181500.0
2  2.0        60.0       RL  ...         0.0       920.0  223500.0
3  3.0        70.0       RL  ...         0.0       756.0  140000.0
4  4.0        60.0       RL  ...         0.0      1145.0  250000.0

[5 rows x 13 columns]

In [78]:
df.isnull().sum()

Id              0
MSSubClass      0
MSZoning        4
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     1
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [79]:
categorical_impute = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = categorical_impute.fit_transform(df[categorical_cols])

In [80]:
df.head(10)

    Id  MSSubClass MSZoning  ...  BsmtFinSF2 TotalBsmtSF SalePrice
0  0.0        60.0       RL  ...         0.0       856.0  208500.0
1  1.0        20.0       RL  ...         0.0      1262.0  181500.0
2  2.0        60.0       RL  ...         0.0       920.0  223500.0
3  3.0        70.0       RL  ...         0.0       756.0  140000.0
4  4.0        60.0       RL  ...         0.0      1145.0  250000.0
5  5.0        50.0       RL  ...         0.0       796.0  143000.0
6  6.0        20.0       RL  ...         0.0      1686.0  307000.0
7  7.0        60.0       RL  ...        32.0      1107.0  200000.0
8  8.0        50.0       RM  ...         0.0       952.0  129900.0
9  9.0       190.0       RL  ...         0.0       991.0  118000.0

[10 rows x 13 columns]

In [104]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["MSZoning"] = le.fit_transform(df["MSZoning"])

df["LotConfig"] = le.fit_transform(df["LotConfig"])

df["Exterior1st"] = le.fit_transform(df["Exterior1st"])

df["BldgType"] = le.fit_transform(df["BldgType"])

In [105]:
df.sample(10)

          Id  MSSubClass  MSZoning  ...  BsmtFinSF2  TotalBsmtSF     SalePrice
1900  1900.0        50.0         3  ...         0.0        840.0  180921.19589
2558  2558.0        30.0         3  ...         0.0       1290.0  180921.19589
348    348.0       160.0         3  ...         0.0        764.0  154000.00000
1888  1888.0        60.0         3  ...         0.0        608.0  180921.19589
1355  1355.0        80.0         3  ...         0.0        570.0  170000.00000
1300  1300.0        60.0         3  ...         0.0        978.0  225000.00000
2179  2179.0        90.0         4  ...       162.0       1838.0  180921.19589
1761  1761.0        60.0         3  ...         0.0        744.0  180921.19589
792    792.0        60.0         3  ...         0.0       1117.0  269790.00000
958    958.0        20.0         3  ...         0.0       1337.0  185000.00000

[10 rows x 13 columns]

In [106]:
df.isnull().sum()

Id              0
MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [107]:
df["Exterior1st"].value_counts()

Exterior1st
12    1026
8      450
6      442
13     411
9      221
5      126
3       87
14      56
0       44
11      43
2        6
1        2
10       2
4        2
7        1
Name: count, dtype: int64

In [108]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'LotConfig', 'BldgType',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'Exterior1st', 'BsmtFinSF2',
       'TotalBsmtSF', 'SalePrice'],
      dtype='object')

In [109]:
X = df.drop(["Id", "SalePrice"], axis=1)
y = df["SalePrice"]

In [110]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [111]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix

log_model = LogisticRegression()

log_model.fit(X_train, y_train)

y_pred = log_model.predict(X_test)

print("Logistics Regression Model")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.