In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [ ]:
df.head() #34 Features and 1 Category means Output

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [5]:
df.shape

(898, 35)

In [4]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [6]:
# Split the dataset
X = df.drop(["Class"], axis=1)
y = df["Class"]

In [7]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [23]:
# APPLY LABEL ENCODER AND STANDARDSCALER
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [26]:
X_train

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,169573,1548.9830,594.8965,364.4516,0.7904,464.6580,0.9932,170738,0.8245,1.6323,...,-0.6257,2.4879,2.1186,2.4125,-35847098368,-33293408256,-27052677120,69.5829,67.4267,61.7498
270,102142,1223.5020,441.7251,296.5040,0.7412,360.6262,0.9863,103559,0.7847,1.4898,...,-0.5385,3.7325,3.9749,3.0696,-20307597312,-20240594944,-18247018496,68.7153,69.4312,65.9034
860,212397,1773.1410,649.3710,418.6798,0.7644,520.0310,0.9773,217331,0.7605,1.5510,...,0.1680,2.8597,2.8887,3.0498,-21660262400,-16450807808,-15513940992,50.1400,43.9826,43.0455
435,441826,2486.4771,942.0581,603.1290,0.7682,750.0336,0.9948,444138,0.8075,1.5620,...,1.7484,7.9695,9.3755,7.3022,-36332118016,-32863416320,-37779701760,43.0456,41.0627,43.2121
102,212744,1720.3030,628.2148,432.3847,0.7254,520.4556,0.9918,214501,0.7818,1.4529,...,-0.2504,1.9579,2.1380,2.4907,-28291532800,-27781709824,-24325011456,55.4153,54.8434,52.6176

In [27]:
y_train

array([6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4, 5, 4, 6, 6,
       4, 2, 5, 5, 5, 4, 4, 2, 4, 6, 5, 6, 2, 0, 5, 1, 4, 3, 1, 2, 6, 2,
       2, 3, 2, 5, 2, 4, 0, 2, 6, 4, 2, 1, 4, 6, 5, 5, 5, 5, 3, 4, 3, 4,
       3, 6, 5, 2, 4, 1, 1, 3, 0, 3, 3, 4, 6, 2, 1, 4, 4, 5, 4, 5, 6, 2,
       3, 5, 2, 2, 4, 6, 2, 6, 1, 6, 2, 5, 5, 1, 1, 3, 6, 1, 2, 0, 4, 2,
       2, 4, 4, 3, 1, 2, 0, 4, 4, 1, 5, 3, 5, 1, 2, 2, 5, 3, 1, 4, 4, 2,
       0, 4, 1, 3, 0, 2, 4, 6, 0, 2, 3, 3, 0, 3, 6, 5, 2, 4, 5, 3, 5, 0,
       5, 4, 1, 0, 2, 2, 2, 5, 0, 2, 4, 4, 2, 4, 5, 5, 3, 4, 4, 2, 4, 5,
       2, 2, 4, 5, 1, 1, 4, 5, 1, 1, 4, 1, 4, 1, 2, 6, 6, 6, 4, 5, 1, 0,
       3, 0, 0, 2, 2, 5, 4, 5, 4, 2, 4, 5, 4, 2, 5, 5, 5, 3, 2, 4, 2, 5,
       0, 0, 3, 2, 4, 6, 5, 3, 2, 6, 6, 5, 2, 4, 0, 2, 0, 2, 2, 4, 5, 6,
       4, 2, 6, 4, 2, 2, 1, 4, 4, 6, 2, 2, 5, 3, 4, 1, 1, 5, 4, 2, 1, 6,
       2, 2, 5, 4, 2, 1, 5, 1, 1, 5, 2, 2, 0, 6, 4, 5, 3, 4, 1, 2, 5, 1,
       2, 5, 5, 4, 4, 2, 2, 5, 1, 5, 6, 6, 5, 3, 2, 5, 2, 3, 2, 2, 0, 2,
       3, 4, 4, 2, 2, 6, 5, 1, 6, 0, 6, 2, 4, 1, 4, 4, 5, 6, 5, 2, 2, 2,
       2, 0, 6, 1, 1, 5, 0, 2, 6, 1, 4, 3, 6, 2, 0, 5, 5, 5, 3, 4, 0, 2,
       2, 5, 4, 5, 5, 1, 2, 4, 0, 1, 2, 2, 4, 6, 2, 1, 5, 2, 2, 5, 5, 5,
       5, 4, 4, 6, 0, 6, 1, 5, 2, 0, 4, 0, 6, 5, 4, 5, 4, 2, 4, 2, 0, 6,
       3, 6, 2, 2, 0, 6, 3, 4, 6, 5, 5, 2, 5, 5, 4, 6, 5, 4, 6, 1, 5, 1,
       6, 5, 5, 1, 2, 5, 1, 3, 3, 4, 1, 0, 1, 3, 6, 2, 5, 5, 0, 5, 0, 4,
       2, 2, 5, 4, 5, 5, 5, 2, 5, 2, 3, 1, 5, 5, 4, 4, 1, 1, 5, 6, 5, 2,
       4, 2, 2, 1, 5, 5, 1, 6, 2, 5, 2, 2, 3, 1, 2, 2, 3, 2, 3, 5, 1, 5,
       3, 5, 5, 6, 2, 5, 6, 5, 6, 5, 5, 5, 3, 6, 4, 2, 5, 4, 4, 1, 2, 5,
       5, 5, 3, 6, 5, 2, 5, 5, 2, 5, 3, 5, 2, 2, 5, 5, 2, 3, 3, 2, 6, 5,
       4, 2, 4, 5, 6, 6, 6, 5, 5, 5, 5, 4, 6, 4, 1, 2, 5, 1, 4, 0, 4, 2,
       5, 5, 5, 6, 5, 1, 4, 2, 4, 5, 4, 4, 5, 2, 3, 3, 5, 2, 0, 5, 5, 5,
       5, 4, 5, 5, 1, 5, 4, 3, 4, 0, 0, 2, 1, 0, 5, 2, 4, 3, 2, 3, 5, 3,
       4, 4, 1, 0, 4, 5, 1, 6, 4, 0, 0, 1, 0, 4, 3, 2, 5, 2, 5, 0, 2, 5,
       5, 5, 2, 5, 2, 5, 4, 4, 6, 2, 2, 1, 4, 5, 3, 5, 4, 5, 1, 4, 3, 0,
       6, 4, 1, 2, 0, 5, 4, 3, 4, 2, 1, 2, 4, 2, 5, 2, 0, 2, 4, 3, 2, 2,
       6, 6, 5, 6, 4, 6, 4, 6, 2, 4, 4, 5, 2, 5, 5, 4, 5, 4, 0, 4, 4, 6,
       5, 2, 0, 2, 4, 1, 2, 2, 3, 6, 3, 4, 2, 5, 2, 5, 1, 5, 6, 1, 3, 1,
       4, 2, 2, 4, 1, 5, 0, 5, 1, 1, 2, 6, 3, 1])

In [28]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [29]:
X_train_scaled

array([[ 0.58688241,  0.77313761,  0.65494348, ...,  0.30093727,
        -0.16212317, -0.02461782],
       [ 0.3914469 ,  0.71185715,  1.13717993, ..., -1.80898088,
        -1.46032963, -1.34892074],
       [-2.06406201, -2.47260549, -2.61727944, ...,  0.29158724,
         0.32348907,  0.24572657],
       ...,
       [-0.8299155 , -0.72527788, -0.73488935, ...,  0.02780714,
        -0.3163686 , -0.44177804],
       [ 1.30943154,  1.02019277,  1.29642401, ..., -0.41235787,
        -0.5222101 , -0.42641305],
       [-0.82667985, -0.85456781, -0.88171807, ...,  0.35510789,
         0.44927523,  0.44102602]])

In [30]:
X_test_scaled

array([[-1.33848733, -1.35843941, -1.47666993, ...,  1.63683812,
         1.82228088,  1.29772857],
       [-0.23902663, -0.08490971,  0.2070367 , ..., -2.25526956,
        -2.01637407, -1.91092123],
       [-1.2414833 , -1.23346059, -1.31278038, ..., -0.21894745,
        -0.23879135, -0.2585369 ],
       ...,
       [-0.30773468, -0.1198062 ,  0.05061721, ...,  0.81534204,
         0.82094001,  0.87201754],
       [ 0.7409328 ,  0.50209343,  0.40677194, ...,  0.06903981,
         0.20670669,  0.1098103 ],
       [-1.2246528 , -1.0791579 , -0.96640986, ...,  1.21502148,
         1.54131208,  1.35056518]])

## START THE ANN FOR CLASSIFICATION

In [31]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [32]:
# CREATE THE TENSOR
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [33]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [34]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

## Build The Model

In [35]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),

            nn.Linear(64, 64),
            nn.ReLU(),

            nn.Linear(64, 7),
        )
    
    def forward(self, x):
        return self.model(x)

In [41]:
model = ANN()

# LOSS & OPTIM
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [42]:
# TRAINING THE NN

epochs = 100

for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    
    train_loss = running_loss / len(train_loader)

    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.724387956702191
epoch = 2/100, loss = 1.161960482597351
epoch = 3/100, loss = 0.7480051789594733
epoch = 4/100, loss = 0.5734683262265247
epoch = 5/100, loss = 0.4793883523215418
epoch = 6/100, loss = 0.4163493241952813
epoch = 7/100, loss = 0.35931825637817383
epoch = 8/100, loss = 0.3254691291114558
epoch = 9/100, loss = 0.2972085462964099
epoch = 10/100, loss = 0.28299541479867435
epoch = 11/100, loss = 0.2643765586873759
epoch = 12/100, loss = 0.24704467343247455
epoch = 13/100, loss = 0.23522752134696298
epoch = 14/100, loss = 0.23951752483844757
epoch = 15/100, loss = 0.21745147523672684
epoch = 16/100, loss = 0.2122336635771005
epoch = 17/100, loss = 0.20683824141388354
epoch = 18/100, loss = 0.19699134645254715
epoch = 19/100, loss = 0.18326127010843027
epoch = 20/100, loss = 0.17409345540015594
epoch = 21/100, loss = 0.17642519671631895
epoch = 22/100, loss = 0.16568647487008054
epoch = 23/100, loss = 0.16808992105981577
epoch = 24/100, loss = 0.15541104421667432
epoch = 25/100, loss = 0.14982133650261423
epoch = 26/100, loss = 0.15518190258223077
epoch = 27/100, loss = 0.14478539626883424
epoch = 28/100, loss = 0.13855481066781541
epoch = 29/100, loss = 0.13759666065806928
epoch = 30/100, loss = 0.1410048780557902
epoch = 31/100, loss = 0.13375911958839581
epoch = 32/100, loss = 0.1286235681694487
epoch = 33/100, loss = 0.11931679486904455
epoch = 34/100, loss = 0.11542503851587357
epoch = 35/100, loss = 0.12462462468639664
epoch = 36/100, loss = 0.11311092430158802
epoch = 37/100, loss = 0.10987859818598499
epoch = 38/100, loss = 0.10808878310996553
epoch = 39/100, loss = 0.10998639561559843
epoch = 40/100, loss = 0.11038466024657954
epoch = 41/100, loss = 0.10487456401081188
epoch = 42/100, loss = 0.10346761742687743
epoch = 43/100, loss = 0.10412984495253666
epoch = 44/100, loss = 0.11035472721509311
epoch = 45/100, loss = 0.09621754142901172
epoch = 46/100, loss = 0.08953394003860328
epoch = 47/100, loss = 0.08968701723801054
epoch = 48/100, loss = 0.09647518906580366
epoch = 49/100, loss = 0.08836548127557921
epoch = 50/100, loss = 0.08681755168768375
epoch = 51/100, loss = 0.078083668956938
epoch = 52/100, loss = 0.08346655896014493
epoch = 53/100, loss = 0.08130926744121572
epoch = 54/100, loss = 0.08424831631228975
epoch = 55/100, loss = 0.07610601624069006
epoch = 56/100, loss = 0.07179181453893366
epoch = 57/100, loss = 0.07319822632100272
epoch = 58/100, loss = 0.07056329404408841
epoch = 59/100, loss = 0.06269850428013699
epoch = 60/100, loss = 0.06402967732561671
epoch = 61/100, loss = 0.06134458396421826
epoch = 62/100, loss = 0.06137603173113387
epoch = 63/100, loss = 0.06736279538144237
epoch = 64/100, loss = 0.060411708550932613
epoch = 65/100, loss = 0.05780565273016691
epoch = 66/100, loss = 0.06739373371490966
epoch = 67/100, loss = 0.05586511471673199
epoch = 68/100, loss = 0.052553467796710523
epoch = 69/100, loss = 0.050198152620831264
epoch = 70/100, loss = 0.052272756300542664
epoch = 71/100, loss = 0.05020675127920897
epoch = 72/100, loss = 0.049275893677511944
epoch = 73/100, loss = 0.047896266024073826
epoch = 74/100, loss = 0.04627410151347842
epoch = 75/100, loss = 0.050462664347951824
epoch = 76/100, loss = 0.0461969183879378
epoch = 77/100, loss = 0.04845862763771868
epoch = 78/100, loss = 0.04299999289619534
epoch = 79/100, loss = 0.041022692462834326
epoch = 80/100, loss = 0.04246305151964012
epoch = 81/100, loss = 0.03834904569363141
epoch = 82/100, loss = 0.037465593453658665
epoch = 83/100, loss = 0.037865726803631886
epoch = 84/100, loss = 0.03579152863391716
epoch = 85/100, loss = 0.03698888951507599
epoch = 86/100, loss = 0.03366558541260336
epoch = 87/100, loss = 0.032940019701567035
epoch = 88/100, loss = 0.03319554881233236
epoch = 89/100, loss = 0.033413958047395165
epoch = 90/100, loss = 0.03391206433551143
epoch = 91/100, loss = 0.03297194036776605
epoch = 92/100, loss = 0.032346897292882204
epoch = 93/100, loss = 0.028917474651952154
epoch = 94/100, loss = 0.032800631435668984
epoch = 95/100, loss = 0.029866013144466862
epoch = 96/100, loss = 0.029271477742282594
epoch = 97/100, loss = 0.029147075246209683
epoch = 98/100, loss = 0.026608453233442877
epoch = 99/100, loss = 0.02870992344358693
epoch = 100/100, loss = 0.026841357041595747

# Evalute the model

In [47]:
# Set model to evaluation mode
# This disables Dropout and BatchNorm training behavior
model.eval()

# Variable to store total number of samples
total = 0 

# Variable to store number of correctly predicted samples
correct = 0

# Disable gradient calculation (saves memory and speeds up inference)
with torch.no_grad():
    
    # Loop through test dataset batch by batch
    for xb, yb in test_loader:
        
        # Forward propagation: get predictions from model
        outputs = model(xb)
        
        # Get the index (class label) of the highest score (logits)
        # torch.max returns (max_value, index)
        # We only need index → predicted class
        _, predicted = torch.max(outputs, 1)

        # Compare predicted labels with actual labels
        # (predicted == yb) gives True/False tensor
        # .sum() counts number of True values (correct predictions)
        # .item() converts tensor to Python integer
        correct += (predicted == yb).sum().item()
        
        # Count total number of samples in this batch
        # yb.size(0) gives batch size
        total += yb.size(0)

# Print total number of samples tested
print("Total Values:", total)

# Print number of correctly predicted samples
print("Correctly Predicted Values:", correct)

# Optional: Print accuracy
print("Test Accuracy: {:.2f}%".format((correct / total) * 100))

Total Values: 180
Correctly Predicted Values: 168
Test Accuracy: 93.33%

In [46]:
print("Accuracy: ", correct / total * 100)

Accuracy:  93.33333333333333